before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/ggdream/gvm.version={{.Version}} -X github.com/ggdream/gvm.commit={{.Commit}} -X github.com/ggdream/gvm.date={{.Date}}
